version: '3'
services:
 python:
   build: .
   tty: true
   working_dir: /code
   ports:
     - 8000:8000
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   image: mysql:5.7
   restart: always
   environment:
    MYSQL_DATABASE: mysql_database
    MYSQL_USER: mysql_user
    MYSQL_PASSWORD: user_password
    MYSQL_ROOT_PASSWORD: root_password
   volumes:
     - ./mysql:/var/lib/mysql
   ports:
     - 3306:3306
