version: '3'
services:
 web:
   build: .
   tty: true
   working_dir: /code
   ports:
     - 8888:8888
   volumes:
     - .:/code
   depends_on:
     - db
 db:
   image: mysql:5.7
   restart: always
   environment:
     MYSQL_DATABASE: python_database
     MYSQL_USER: root
     MYSQL_PASSWORD: password
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   volumes:
     - ./mysql:/var/lib/mysql
   ports:
     - 333306:3306